<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>annotations</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>SunamoDevCode</AssemblyName>
    <RootNamespace>SunamoDevCode</RootNamespace>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <IsPackable>false</IsPackable>
    <DefineConstants>$(DefineConstants);ASYNC</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\SunamoDevCode\SunamoDevCode\**\*.cs"
             Exclude="..\SunamoDevCode\SunamoDevCode\obj\**\*;
                      ..\SunamoDevCode\SunamoDevCode\bin\**\*;
                      ..\SunamoDevCode\SunamoDevCode\Aps\**\*.cs;
                      ..\SunamoDevCode\SunamoDevCode\SunamoSolutionsIndexer\**\*.cs;
                      ..\SunamoDevCode\SunamoDevCode\ToNetCore\**\*.cs;
                      ..\SunamoDevCode\SunamoDevCode\GlobalUsings.cs;
                      ..\SunamoDevCode\SunamoDevCode\ConstsManager.cs;
                      ..\SunamoDevCode\SunamoDevCode\CSharpGenerator1.cs;
                      ..\SunamoDevCode\SunamoDevCode\CSharpGenerator2.cs;
                      ..\SunamoDevCode\SunamoDevCode\CSharpParser.cs;
                      ..\SunamoDevCode\SunamoDevCode\FileFormats\XmlLocalisationInterchangeFileFormat21.cs;
                      ..\SunamoDevCode\SunamoDevCode\FileFormats\XmlLocalisationInterchangeFileFormat22.cs;
                      ..\SunamoDevCode\SunamoDevCode\FileFormats\XmlLocalisationInterchangeFileFormat23.cs;
                      ..\SunamoDevCode\SunamoDevCode\FileFormats\XmlLocalisationInterchangeFileFormat24.cs;
                      ..\SunamoDevCode\SunamoDevCode\FileFormats\XmlLocalisationInterchangeFileFormat25.cs;
                      ..\SunamoDevCode\SunamoDevCode\GlobalUsingsInstance.cs;
                      ..\SunamoDevCode\SunamoDevCode\PpkOnDriveDC.cs;
                      ..\SunamoDevCode\SunamoDevCode\PpkOnDriveDevCodeBase.cs;
                      ..\SunamoDevCode\SunamoDevCode\Services\AddOrEditNamespaceService.cs;
                      ..\SunamoDevCode\SunamoDevCode\SunamoCSharp\CSharpHelper.cs;
                      ..\SunamoDevCode\SunamoDevCode\SunamoCSharp\CSharpHelper3.cs;
                      ..\SunamoDevCode\SunamoDevCode\TFCsFormat.cs;
                      ..\SunamoDevCode\SunamoDevCode\XmlDocumentsCache.cs;
                      ..\SunamoDevCode\SunamoDevCode\XmlLocalisationInterchangeFileFormatSunamo.cs;
                      ..\SunamoDevCode\SunamoDevCode\Unindexable.cs;
                      ..\SunamoDevCode\SunamoDevCode\UnindexableHelper.cs;
                      ..\SunamoDevCode\SunamoDevCode\ReplacerXlf.cs;
                      ..\SunamoDevCode\SunamoDevCode\_sunamo\SHJoin.cs;
                      ..\SunamoDevCode\SunamoDevCode\_sunamo\SunamoXml\XHelper.cs;
                      ..\SunamoDevCode\SunamoDevCode\_sunamo\SunamoXml\XHelper1.cs;
                      ..\SunamoDevCode\SunamoDevCode\_sunamo\TF.cs;
                      ..\SunamoDevCode\SunamoDevCode\CSharpGenerator.cs;
                      ..\SunamoDevCode\SunamoDevCode\CSharpGenerator3.cs;
                      ..\SunamoDevCode\SunamoDevCode\FileFormats\XlfData.cs;
                      ..\SunamoDevCode\SunamoDevCode\FileFormats\XmlLocalisationInterchangeFileFormat2.cs;
                      ..\SunamoDevCode\SunamoDevCode\GetSlns.cs;
                      ..\SunamoDevCode\SunamoDevCode\SunamoCSharp\CSharpHelper1.cs;
                      ..\SunamoDevCode\SunamoDevCode\SunamoCSharp\CSharpHelper2.cs;
                      ..\SunamoDevCode\SunamoDevCode\_public\ResultWithExceptionDC.cs;
                      ..\SunamoDevCode\SunamoDevCode\CodeGenerator\CSharpClassesGenerator.cs;
                      ..\SunamoDevCode\SunamoDevCode\CsprojShared.cs;
                      ..\SunamoDevCode\SunamoDevCode\GetCsprojs.cs;
                      ..\SunamoDevCode\SunamoDevCode\GetCsprojsInSolution.cs;
                      ..\SunamoDevCode\SunamoDevCode\_public\SunamoGitBashBuilder\**\*.cs;
                      ..\SunamoDevCode\SunamoDevCode\GitHelper.cs" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="SunamoDevCode.GlobalUsings.Net48.cs" />
    <Compile Include="SunamoDevCode.Compat.Net48.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CaseDotNet" Version="0.3.36" />
    <PackageReference Include="CaseDotNet.Extensions" Version="0.2.46" />
    <PackageReference Include="Diacritics" Version="4.1.4" />
    <PackageReference Include="Google.Apis.Core" Version="1.68.0" />
    <PackageReference Include="HtmlAgilityPack" Version="1.12.4" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.0" />
    <PackageReference Include="ResXResourceReader.NetStandard" Version="1.2.0" />
    <PackageReference Include="TextCopy" Version="6.2.1" />
  </ItemGroup>
</Project>