global using System;
global using System.Linq;
global using System.Text;
global using System.Collections;
global using System.Collections.Generic;
global using System.Diagnostics.CodeAnalysis;
global using System.Reflection;
global using System.Net;
global using System.Diagnostics;