
namespace SunamoCssGenerator;
public class PropertiesConversions
{
	static Dictionary<string, string> dict = new Dictionary<string, string>();

	/// <summary>
	/// Before first calling must call Init()
	/// </summary>
	/// <param name="s"></param>
	/// <returns></returns>
	public static string Convert(string s)
    {
		return dict[s];
    }

	public static void Init()
	{
		dict.Add("AlignContent", "align-content");
		dict.Add("AlignItems", "align-items");
		dict.Add("AlignSelf", "align-self");
		dict.Add("Animation", "animation");
		dict.Add("AnimationDelay", "animation-delay");
		dict.Add("AnimationDirection", "animation-direction");
		dict.Add("AnimationDuration", "animation-duration");
		dict.Add("AnimationFillMode", "animation-fill-mode");
		dict.Add("AnimationIterationCount", "animation-iteration-count");
		dict.Add("AnimationName", "animation-name");
		dict.Add("AnimationPlayState", "animation-play-state");
		dict.Add("AnimationTimingFunction", "animation-timing-function");
		dict.Add("BackfaceVisibility", "backface-visibility");
		dict.Add("Background", "background");
		dict.Add("BackgroundAttachment", "background-attachment");
		dict.Add("BackgroundClip", "background-clip");
		dict.Add("BackgroundColor", "background-color");
		dict.Add("BackgroundImage", "background-image");
		dict.Add("BackgroundOrigin", "background-origin");
		dict.Add("BackgroundPosition", "background-position");
		dict.Add("BackgroundRepeat", "background-repeat");
		dict.Add("BackgroundSize", "background-size");
		dict.Add("Border", "border");
		dict.Add("BorderBottom", "border-bottom");
		dict.Add("BorderBottomColor", "border-bottom-color");
		dict.Add("BorderBottomLeftRadius", "border-bottom-left-radius");
		dict.Add("BorderBottomRightRadius", "border-bottom-right-radius");
		dict.Add("BorderBottomStyle", "border-bottom-style");
		dict.Add("BorderBottomWidth", "border-bottom-width");
		dict.Add("BorderCollapse", "border-collapse");
		dict.Add("BorderColor", "border-color");
		dict.Add("BorderImage", "border-image");
		dict.Add("BorderImageOutset", "border-image-outset");
		dict.Add("BorderImageRepeat", "border-image-repeat");
		dict.Add("BorderImageSlice", "border-image-slice");
		dict.Add("BorderImageSource", "border-image-source");
		dict.Add("BorderImageWidth", "border-image-width");
		dict.Add("BorderLeft", "border-left");
		dict.Add("BorderLeftColor", "border-left-color");
		dict.Add("BorderLeftStyle", "border-left-style");
		dict.Add("BorderLeftWidth", "border-left-width");
		dict.Add("BorderRadius", "border-radius");
		dict.Add("BorderRight", "border-right");
		dict.Add("BorderRightColor", "border-right-color");
		dict.Add("BorderRightStyle", "border-right-style");
		dict.Add("BorderRightWidth", "border-right-width");
		dict.Add("BorderSpacing", "border-spacing");
		dict.Add("BorderStyle", "border-style");
		dict.Add("BorderTop", "border-top");
		dict.Add("BorderTopColor", "border-top-color");
		dict.Add("BorderTopLeftRadius", "border-top-left-radius");
		dict.Add("BorderTopRightRadius", "border-top-right-radius");
		dict.Add("BorderTopStyle", "border-top-style");
		dict.Add("BorderTopWidth", "border-top-width");
		dict.Add("BorderWidth", "border-width");
		dict.Add("Bottom", "bottom");
		dict.Add("BoxShadow", "box-shadow");
		dict.Add("BoxSizing", "box-sizing");
		dict.Add("CaptionSide", "caption-side");
		dict.Add("Clear", "clear");
		dict.Add("Clip", "clip");
		dict.Add("Color", "color");
		dict.Add("ColumnCount", "column-count");
		dict.Add("ColumnFill", "column-fill");
		dict.Add("ColumnGap", "column-gap");
		dict.Add("ColumnRule", "column-rule");
		dict.Add("ColumnRuleColor", "column-rule-color");
		dict.Add("ColumnRuleStyle", "column-rule-style");
		dict.Add("ColumnRuleWidth", "column-rule-width");
		dict.Add("ColumnSpan", "column-span");
		dict.Add("ColumnWidth", "column-width");
		dict.Add("Columns", "columns");
		dict.Add("Content", "content");
		dict.Add("CounterIncrement", "counter-increment");
		dict.Add("CounterReset", "counter-reset");
		dict.Add("Cursor", "cursor");
		dict.Add("Direction", "direction");
		dict.Add("Display", "display");
		dict.Add("EmptyCells", "empty-cells");
		dict.Add("Flex", "flex");
		dict.Add("FlexBasis", "flex-basis");
		dict.Add("FlexDirection", "flex-direction");
		dict.Add("FlexFlow", "flex-flow");
		dict.Add("FlexGrow", "flex-grow");
		dict.Add("FlexShrink", "flex-shrink");
		dict.Add("FlexWrap", "flex-wrap");
		dict.Add("Float", "float");
		dict.Add("Font", "font");
		dict.Add("FontFamily", "font-family");
		dict.Add("FontSize", "font-size");
		dict.Add("FontSizeAdjust", "font-size-adjust");
		dict.Add("FontStretch", "font-stretch");
		dict.Add("FontStyle", "font-style");
		dict.Add("FontVariant", "font-variant");
		dict.Add("FontWeight", "font-weight");
		dict.Add("Height", "height");
		dict.Add("JustifyContent", "justify-content");
		dict.Add("Left", "left");
		dict.Add("LetterSpacing", "letter-spacing");
		dict.Add("LineHeight", "line-height");
		dict.Add("ListStyle", "list-style");
		dict.Add("ListStyleImage", "list-style-image");
		dict.Add("ListStylePosition", "list-style-position");
		dict.Add("ListStyleType", "list-style-type");
		dict.Add("Margin", "margin");
		dict.Add("MarginBottom", "margin-bottom");
		dict.Add("MarginLeft", "margin-left");
		dict.Add("MarginRight", "margin-right");
		dict.Add("MarginTop", "margin-top");
		dict.Add("MaxHeight", "max-height");
		dict.Add("MaxWidth", "max-width");
		dict.Add("MinHeight", "min-height");
		dict.Add("MinWidth", "min-width");
		dict.Add("Opacity", "opacity");
		dict.Add("Order", "order");
		dict.Add("Outline", "outline");
		dict.Add("OutlineColor", "outline-color");
		dict.Add("OutlineOffset", "outline-offset");
		dict.Add("OutlineStyle", "outline-style");
		dict.Add("OutlineWidth", "outline-width");
		dict.Add("Overflow", "overflow");
		dict.Add("OverflowX", "overflow-x");
		dict.Add("OverflowY", "overflow-y");
		dict.Add("Padding", "padding");
		dict.Add("PaddingBottom", "padding-bottom");
		dict.Add("PaddingLeft", "padding-left");
		dict.Add("PaddingRight", "padding-right");
		dict.Add("PaddingTop", "padding-top");
		dict.Add("PageBreakAfter", "page-break-after");
		dict.Add("PageBreakBefore", "page-break-before");
		dict.Add("PageBreakInside", "page-break-inside");
		dict.Add("Perspective", "perspective");
		dict.Add("PerspectiveOrigin", "perspective-origin");
		dict.Add("Position", "position");
		dict.Add("Quotes", "quotes");
		dict.Add("Resize", "resize");
		dict.Add("Right", "right");
		dict.Add("TabSize", "tab-size");
		dict.Add("TableLayout", "table-layout");
		dict.Add("TextAlign", "text-align");
		dict.Add("TextAlignLast", "text-align-last");
		dict.Add("TextDecoration", "text-decoration");
		dict.Add("TextDecorationColor", "text-decoration-color");
		dict.Add("TextDecorationLine", "text-decoration-line");
		dict.Add("TextDecorationStyle", "text-decoration-style");
		dict.Add("TextIndent", "text-indent");
		dict.Add("TextJustify", "text-justify");
		dict.Add("TextOverflow", "text-overflow");
		dict.Add("TextShadow", "text-shadow");
		dict.Add("TextTransform", "text-transform");
		dict.Add("Top", "top");
		dict.Add("Transform", "transform");
		dict.Add("TransformOrigin", "transform-origin");
		dict.Add("TransformStyle", "transform-style");
		dict.Add("Transition", "transition");
		dict.Add("TransitionDelay", "transition-delay");
		dict.Add("TransitionDuration", "transition-duration");
		dict.Add("TransitionProperty", "transition-property");
		dict.Add("TransitionTimingFunction", "transition-timing-function");
		dict.Add("VerticalAlign", "vertical-align");
		dict.Add("Visibility", "visibility");
		dict.Add("WhiteSpace", "white-space");
		dict.Add("Width", "width");
		dict.Add("WordBreak", "word-break");
		dict.Add("WordSpacing", "word-spacing");
		dict.Add("WordWrap", "word-wrap");
		dict.Add("ZIndex", "z-index");
	}

}
